name: 'transformacao_bps'
version: '1.0.0'
config-version: 2

profile: 'transformacao_bps'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  transformacao_bps:
    staging:
      +materialized: view
    marts:
      +materialized: table
